### ISSUE TITLE
mybatis will apper an error

### ISSUE THREAD

**Issue by Aurorxa** [testcontainers/testcontainers-java-spring-boot-quickstart#12]
![image](https://github.com/testcontainers/testcontainers-java-spring-boot-quickstart/assets/25677587/ef293721-d3c1-4d98-877e-ff5090c7dea4)

My Project is there ，https://github.com/Aurorxa/mybatis-flex-springboot3

**Comment by kiview** [comment]
I get an 404 for the project.
Also, this guide does not relate to MyBatis, so I will close the issue here.

You can join the [Testcontainers Slack](https://slack.testcontainers.org/) and ask the community for help for you project.

From the error, it looks to me like you did not configure the Datasource URL to use a database, which is probably an error unrelated to MyBatis.

**Comment by Aurorxa** [comment]
sorry，GitHub action is busy now，so i delete the project ，this is new project address https://github.com/Aurorxa/mybatisflex-springboot3

**Comment by Aurorxa** [comment]
the junit devmode file address is mysql/mysql-base/src/test/java/com/github/mysql/dev ，when i run this， springboot give me tips ，i should Configure MySQL information ，but jpa is OK （ this is only have pear jpa project ，https://github.com/Aurorxa/springboot3-testcontainer ）

**Comment by kiview** [comment]
From the last project you shared, I tried out `ApplicationTest` and it works without issues. I also tried out `LocalDevTestApplication` and the app starts without issues. So what is your actual issue here?
